channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=24.2
- pip:
  - mlflow==2.18.0
  - cffi==1.17.1
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - lightgbm==4.5.0
  - matplotlib==3.9.2
  - my-functions==0.1.0
  - numpy==1.26.4
  - packaging==24.1
  - pandas==2.2.3
  - psutil==5.9.0
  - pyarrow==16.1.0
  - pyyaml==6.0.2
  - scikit-learn==1.5.1
  - scipy==1.14.1
name: mlflow-env
