channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=24.2
- pip:
  - mlflow==2.17.1
  - cffi==1.17.1
  - cloudpickle==3.0.0
  - colorama==0.4.6
  - cytoolz==0.12.2
  - dask-expr==1.1.0
  - defusedxml==0.7.1
  - distributed==2024.5.0
  - jinja2==3.1.4
  - lightgbm==4.5.0
  - lz4==4.3.2
  - matplotlib==3.9.2
  - numpy==1.26.4
  - pandas==2.2.2
  - pathlib==1.0.1
  - pyarrow==14.0.2
  - python-snappy==0.6.1
  - scikit-learn==1.5.0
  - scipy==1.13.1
  - xxhash==2.0.2
  - zstandard==0.23.0
name: mlflow-env
